name: Run Desktop on Lambda Test

on:
  schedule:
    - cron: '0 */7 * * *'  # Runs at minute 0 past every 3rd hour

jobs:
  build:
    runs-on: windows-latest  # Specifies the Windows runner

    steps:
      - uses: actions/checkout@v3
        with:
          ref: mobile_runs  # Specifies the branch to check out

      - name: Set up JDK 11  # Sets up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # AdoptOpenJDK's new project name

      - name: Run Mobile on Lambda Test
        run: |
          ./gradlew clean runDesktopOnLambdaTest "-PuserName=shubhamr" "-PaccessKey=dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh" "-Pplatform=ios" -Pbrowser=Safari "-PbrowserVersion=16.0" -Presolution=2560x1440 "-PrunName=Serenity Local"
        shell: bash  # Ensures the use of Bash shell even on Windows
